thieleju/statsbot

- README.md
- commands/programmingcontests.js
- package-lock.json
- package.json
Closes #13. 
I'm using third-party library [luxon](https://moment.github.io/luxon) to handle dates and time. I hope this is okay.
Preview of the command 
Also there is an option to choose the platform of contests
and the amout of contests to show (default is five)
> Programming contests command

- README.md
- commands/trivia.js
- index.js
- Created the trivia command
- fetched the question and also display the category in the question
- user can answer by reacting to the question ✅ or ❌
- It instantly replies with correct or wrong answer
- Had to make changes in index.js file, changes in GateWayIntentBits.
> created command trivia

- README.md
- commands/catfact.js
- package.json
**Add `/catfact` command** **which shows random facts on cats using Meowfacts**
1. Create a file `catfact.js` on `commands/ ` .
2. Make a GET request with Axios to the Meowfacts API
3. On getting a response, we display the message `interaction.reply(response.data.data[0])`
4. Finally update the README.md file
> Added /catfact command

- README.md
- commands/dogfact.js
Closes #21 
- added commands/dogfact.js
- changed README.md
> feat: dogfact

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- commands/dictionary.js
Removed the debug console and added command to the readme file.
> Dictionary mod

- commands/dictionary.js
Added dictionary command that takes a word and returns the definitions and synonyms in embeds.
> added dictionary command

- README.md
- commands/foxpic.js
> Added foxpic command

- README.md
- commands/mathquestion.js
- index.js
I added the /mathquestion command refering to #16.
Features:
Optional command options:
min --> The minimum number a user wants to play with. 
max --> The maximum number a user wants to play with. 
mode --> easy: 30 seconds to answer, medium: 20 seconds to answer, hard: 10 seconds to answer.
By default the min. number will be 20 and the max. number will be 400. Also the mode will be easy (30 seconds to reply).
Some Example Images:
[details]
> Added /mathquestion command

- README.md
- commands/uptime.js
- package-lock.json
- package.json
Implemented the uptime command using Javascript Date class and [CountdownJS](https://www.npmjs.com/package/countdown)
This closes #48
> :robot: added /uptime command

- README.md
- commands/motivation.js
[[details]
](https://github.com/thieleju/statsbot/issues/30)
> Add motivation command and update readme

- README.md
- commands/breakingbad.js
- [ ✔️] Code is formatted correctly
- [✔️ ] Code is tested before submitting
- [✔️ ] Updated README.md commands list with my new command
#31 
I have added command that generates random Breaking Bad quote. You can see formatting on the attached image.
> Added breakingbad command

- README.md
- commands/catpic.js
> Add /catpic command

- .github/ISSUE_TEMPLATE/BUG.yml
This pull request contains a new template for reporting bugs.
See screenshot below
> Add an issue template for reporting bugs

- README.md
- commands/animequote.js
This command generates a random anime quote or will fetch a quote from your favorite anime! 
Enhancement for issue #40
> Add command /animequote which sends random anime quotes

- README.md
- commands/websiteicon.js
> Created webicon.js

- README.md
- commands/guessage.js
> Add /guessage command using agify.io API

- README.md
- commands/techy.js
Issue: #89
Writing /techy shows a randomly generated tech-savvy phrase.
> Added tech-savvy phrases with the TechyAPI

- README.md
- commands/affirmation.js
Issue: #90 
Bot will fetch random affirmation quote from the Affirmation Dev API
> Add /affirmation command to the bot

- README.md
- commands/series.js
The user enters the name of the series to lookup using the `/series` command and the bot shows an embed with the series name, description, cover image, rating, status, previous and next episode name and release dates.
This is in reference to [this issue](https://github.com/thieleju/statsbot/issues/78)
> added /series command

- README.md
> fix(readme): meme link fix

- README.md
- commands/serverip.js
> Add serverip command

- README.md
- commands/guessnationality.js
- package-lock.json
Issue: #112
The new command /guessnationality includes an option for the user to enter a specific name. If the user does not enter a specific name, the command automatically retrieves a random name from the random-data-api which is an idea I got from the developer who added the /guessage command. These details have also been reflected in the README file.
> Add the /guessnationality bot command

- README.md
- commands/countryInfo.js
- package-lock.json
> Added /countryinfo [country] command to your bot

- README.md
- commands/advice.js
Issue: #117 
The command gives the user a random advice.
> Add /advice command

- README.md
- commands/yesno.js
Issue: #118 
- Added /yesno command with https://yesno.wtf/api
> Yesno command

- README.md
- commands/breakingbaddeath.js
Issue: #125
Shows a random death reason of a Breaking Bad character
> Breakingbaddeath

- README.md
- commands/xkcd.js
Issue: #122
Shows the user a random xkcd comic.
> Add /xkcd command

- README.md
- commands/roboavatar.js
Issue: #120
Added Command /roboavatar
> roboavatar added comand

- README.md
- commands/inspiration.js
Issue: #134
Added a command that gives you inspiration in
> added inspiration command

- index.js
> added Status

- README.md
- commands/encryption.js
Issue: #137 
This command allows you to encrypt/decrypt a message with a key. It also allows you to generate a randomized key.
> Add /encryption command

- README.md
- commands/horoscope.js
Issue: #87 
This command allows you to view daily horoscopes for yesterday, today, and tomorrow.
> Added horoscope command

- README.md
- commands/apod.js
Issue: #53
Since the NASA API key is free(essentially public), I have included it within this. This should ensure the program will run with maximum efficiency and you don't have to store anything locally
> NASA APOD addition

- README.md
- commands/apod.js
- commands/truefact.js
> added truefact command

- README.md
- commands/createloripsum.js
Issue: #133
Create a Loripsum textfield with number of paragraphs equal one and selectable paragraph length (short, medium, long)
> createloripsum added comand

- README.md
- commands/urban.js
> add urban dictionary api

- README.md
- commands/genderofname.js
- commands/guessgender.js
> add Genderize API

- README.md
- commands/shortenlink.js
> Added /shortenlink Command

- README.md
- commands/universitydomain.js
> Add /Universitydomain command

- README.md
- commands/locateiss.js
> add /locateiss comand
